#!/usr/sgug/bin/bash

export CFLAGS="-I/usr/sgug/include/libdicl-0.1 -D_SGI_SOURCE -D_SGI_MP_SOURCE -D_SGI_REENTRANT_FUNCTIONS -Og -g"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-ldicl-0.1 -liconv -Wl,-z,relro"
export SHELL=/usr/sgug/bin/sh
export CONFIG_SHELL="$SHELL"
export SHELL_PATH="$SHELL"
export PERL=/usr/sgug/bin/perl
export MAKE_NUM=5
#export MAKE_NUM=1

# "DEEP_DEBUG"
#make -j$MAKE_NUM V=1 PREFIX=/usr/sgug NETSURF_USE_WEBP=YES NETSURF_USE_NSSVG=YES NETSURF_USE_ROSPRITE=NO NETSURF_USE_NSPSL=YES NETSURF_USE_NSLOG=YES NETSURF_USE_HARU_PDF=NO NETSURF_USE_VIDEO=NO TARGET=gtk3 NETSURF_USE_RSVG=YES NETSURF_USE_WEBP=YES NETSURF_USE_NSSVG=NO NETSURF_USE_ROSPRITE=NO NETSURF_USE_NSPSL=YES NETSURF_USE_NSLOG=YES NETSURF_USE_HARU_PDF=NO NETSURF_USE_VIDEO=NO NETSURF_USE_IPV6=NO NETSURF_USE_DUKTAPE=NO NETSURF_LOG_LEVEL=DEEPDEBUG
make -j$MAKE_NUM V=1 PREFIX=/usr/sgug NETSURF_USE_WEBP=YES NETSURF_USE_NSSVG=YES NETSURF_USE_ROSPRITE=NO NETSURF_USE_NSPSL=YES NETSURF_USE_NSLOG=YES NETSURF_USE_HARU_PDF=NO NETSURF_USE_VIDEO=NO TARGET=gtk3 NETSURF_USE_RSVG=YES NETSURF_USE_WEBP=YES NETSURF_USE_NSSVG=NO NETSURF_USE_ROSPRITE=NO NETSURF_USE_NSPSL=YES NETSURF_USE_NSLOG=YES NETSURF_USE_HARU_PDF=NO NETSURF_USE_VIDEO=NO NETSURF_USE_IPV6=NO NETSURF_USE_DUKTAPE=NO
