#!/usr/sgug/bin/bash

export CFLAGS="-Og -g"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-Wl,-z,relro"
export CPPFLAGS="-I/usr/sgug/include/libdicl-0.1 -D_SGI_SOURCE -D_SGI_MP_SOURCE -D_SGI_REENTRANT_FUNCTIONS"

make -j5 V=1 PREFIX=/usr/sgug NETSURF_USE_WEBP=YES NETSURF_USE_NSSVG=YES NETSURF_USE_ROSPRITE=NO NETSURF_USE_NSPSL=YES NETSURF_USE_NSLOG=YES NETSURF_USE_HARU_PDF=NO NETSURF_USE_VIDEO=NO TARGET=gtk3 NETSURF_USE_RSVG=YES NETSURF_USE_WEBP=YES NETSURF_USE_NSSVG=NO NETSURF_USE_ROSPRITE=NO NETSURF_USE_NSPSL=YES NETSURF_USE_NSLOG=YES NETSURF_USE_HARU_PDF=NO NETSURF_USE_VIDEO=NO NETSURF_USE_IPV6=NO NETSURF_USE_DUKTAPE=NO
